version: "3.9"

services:
  frontend:
    container_name: frontend
    build: ./docker/frontend
    volumes:
      - .:/app:cached
    ports:
      - "5173:5173"
      - "24678:24678"
    tty: true
    command: sh -c "npm install && npm run dev"

  nginx:
    container_name: nginx
    image: nginx:latest
    volumes:
    #  - ./nginx/conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
    ports:
      - "80:80"
    depends_on:
      - frontend

