version: "3.9"

services:
  frontend:
    container_name: frontend
    build: ./docker/frontend
    volumes:
      - ./react:/app:cached
    ports:
      - "5173:5173"
      - "24678:24678"
    tty: true
    command: sh -c "npm install && npm run dev"

  nginx:
    container_name: nginx
    image: nginx:latest
    volumes:
    #  - ./nginx/conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
    ports:
      - "80:80"
    depends_on:
      - frontend

  api:
     build:  ./django
     expose:
       - "8000"
     volumes:
       - ./app:/code
     hostname: app-server
     restart: always

  db:
    image: mysql:latest
    volumes:
      - ./mysql-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=mysql
      - MYSQL_DATABASE=app
      - MYSQL_USER=user
      - MYSQL_PASSWORD=user
    ports:
      - "3306:3306"

